# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Os Paxariños
email: ospaxarinhos@gmail.com
description:  <center><h2>Blog da Casa niño "Os paxariños".</h2></center>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://byemege.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: ['.htaccess']

google_analytics: UA-96802447-1

staticman:
  branch: "master"
  filename: comment-{@timestamp}
  commitMessage: "new comment."
  format: "yml"
  allowedFields: ["name", "email", "message"]
  requiredFields: ["name", "email", "message"]
  generatedFields:
    postTime:
      type: "date"
      options:
        format: "timestamp"
  path: "_data/comments/{options.slug}"
  moderation: true
  transforms:
    email: "md5"